name: Build Cordova Android APK

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK components
      run: |
        export ANDROID_SDK_ROOT=/usr/local/lib/android/sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "cmdline-tools;latest" \
          "platforms;android-35" \
          "build-tools;35.0.0" \
          "platform-tools"

    - name: Ensure system dependencies for Cordova Android
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk gradle zipalign

    - name: Install Cordova and global dependencies
      run: npm install -g cordova@12 appium wait-on wd

    - name: Install dependencies
      run: npm install

    - name: Clean and re-add Android platform
      run: |
        cordova platform remove android || true
        cordova platform add android@14 --save

    - name: Build APK
      run: cordova build android
      env:
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.15-6/x64

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cordova-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

    - name: Set up Android Emulator and run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Nexus 6
        script: |
          # Install Appium driver
          appium driver install uiautomator2
          
          # Start Appium with explicit host and port
          appium --address 127.0.0.1 --port 4723 --log-level debug > appium.log 2>&1 &
          
          # Give Appium time to start
          sleep 10
          
          # Check if Appium is running
          ps aux | grep appium
          
          # Try to connect multiple times
          for i in {1..5}; do
            if curl -s http://127.0.0.1:4723/status > /dev/null; then
              echo "Appium server is running"
              break
            else
              echo "Attempt $i: Waiting for Appium server..."
              sleep 10
            fi
          done
          
          # Wait for device
          adb wait-for-device
          adb devices
          
          # Show Appium logs for debugging
          echo "===== Appium Log Output ====="
          cat appium.log
          echo "===== Appium Log Finished ====="
          
          # Install test dependencies
          npm install --save-dev @wdio/cli webdriverio @wdio/local-runner @wdio/mocha-framework
          
          # Run tests
          APPIUM_HOST=127.0.0.1 APPIUM_PORT=4723 npx mocha test/test_wdio.js --timeout 300000
