name: Build Cordova Android APK

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Cordova
      run: npm install -g cordova appium wait-on

    - name: Install dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android

    - name: Build APK
      run: cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: cordova-apk
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

    - name: Set up Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: default
        arch: x86_64
        profile: Nexus 6
        script: |
          # Start Appium server in background
          appium --log-level info > appium.log 2>&1 &
    
          # Wait for Appium server to be ready
          wait-on http://localhost:5554/wd/hub/status
    
          # Run your tests
          npx mocha test/appium.test.js


    
